name: Blog Post Workflow
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update the README with latest Medium posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://naveenvenkatesan.medium.com/feed"